// <auto-generated />
using FundedEdge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using System;
using TrackRecord.Infrastructure.Persistence;

#nullable disable

namespace TrackRecord.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FundedEdgeDbContext))]
    [Migration("20260713120000_AddPeerSharingFlags")]
    partial class AddPeerSharingFlags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.AccountCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("PaidOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "PaidOn");

                    b.ToTable("AccountCosts", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.AccountEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStage")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ToStage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "OccurredAt");

                    b.ToTable("AccountEvents", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.AiReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AiReports", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.DailyMindsetCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DominantPreMarketEmotion")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalStress")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PreMarketFocus")
                        .HasColumnType("integer");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailyMindsetCheckIns", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.EvaluationProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccountSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ActivationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ConsistencyMaxDayFraction")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal?>("DailyLossLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DrawdownType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("EvaluationCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FundedDailyLossLimit")
                        .HasColumnType("numeric");

                    b.Property<int?>("FundedDrawdownType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FundedMaxDrawdown")
                        .HasColumnType("numeric");

                    b.Property<int?>("FundedMinTradingDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FundedProfitTarget")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinTradingDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PayoutMaxProfitPct")
                        .HasColumnType("numeric");

                    b.Property<int?>("PayoutMinDaysBetween")
                        .HasColumnType("integer");

                    b.Property<decimal>("PayoutSplitTraderPct")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ProfitTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PropFirmId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PropFirmId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropFirmId1");

                    b.HasIndex("PropFirmId", "IsActive");

                    b.ToTable("EvaluationPrograms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000015"),
                            AccountSize = 25000m,
                            ActivationCost = 130m,
                            ConsistencyMaxDayFraction = 0.30m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 147m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 1500m,
                            FundedMinTradingDays = 7,
                            IsActive = true,
                            MaxDrawdown = 1500m,
                            MinTradingDays = 7,
                            Name = "Apex 25K",
                            PayoutMinDaysBetween = 7,
                            PayoutSplitTraderPct = 1.00m,
                            ProfitTarget = 1500m,
                            PropFirmId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            AccountSize = 50000m,
                            ActivationCost = 130m,
                            ConsistencyMaxDayFraction = 0.30m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 167m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 2500m,
                            FundedMinTradingDays = 7,
                            IsActive = true,
                            MaxDrawdown = 2500m,
                            MinTradingDays = 7,
                            Name = "Apex 50K",
                            PayoutMinDaysBetween = 7,
                            PayoutSplitTraderPct = 1.00m,
                            ProfitTarget = 3000m,
                            PropFirmId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            AccountSize = 100000m,
                            ActivationCost = 130m,
                            ConsistencyMaxDayFraction = 0.30m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 207m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 3000m,
                            FundedMinTradingDays = 7,
                            IsActive = true,
                            MaxDrawdown = 3000m,
                            MinTradingDays = 7,
                            Name = "Apex 100K",
                            PayoutMinDaysBetween = 7,
                            PayoutSplitTraderPct = 1.00m,
                            ProfitTarget = 6000m,
                            PropFirmId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000016"),
                            AccountSize = 150000m,
                            ActivationCost = 130m,
                            ConsistencyMaxDayFraction = 0.30m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 297m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 5000m,
                            FundedMinTradingDays = 7,
                            IsActive = true,
                            MaxDrawdown = 5000m,
                            MinTradingDays = 7,
                            Name = "Apex 150K",
                            PayoutMinDaysBetween = 7,
                            PayoutSplitTraderPct = 1.00m,
                            ProfitTarget = 9000m,
                            PropFirmId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000017"),
                            AccountSize = 25000m,
                            ActivationCost = 0m,
                            DailyLossLimit = 600m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 130m,
                            FundedDailyLossLimit = 600m,
                            FundedDrawdownType = 1,
                            FundedMaxDrawdown = 1000m,
                            IsActive = true,
                            MaxDrawdown = 1000m,
                            MinTradingDays = 5,
                            Name = "Tradeify Growth 25K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 1500m,
                            PropFirmId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            AccountSize = 50000m,
                            ActivationCost = 0m,
                            DailyLossLimit = 1250m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 165m,
                            FundedDailyLossLimit = 1250m,
                            FundedDrawdownType = 1,
                            FundedMaxDrawdown = 2000m,
                            IsActive = true,
                            MaxDrawdown = 2000m,
                            MinTradingDays = 5,
                            Name = "Tradeify Growth 50K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 3000m,
                            PropFirmId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            AccountSize = 100000m,
                            ActivationCost = 0m,
                            DailyLossLimit = 2500m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 219m,
                            FundedDailyLossLimit = 2500m,
                            FundedDrawdownType = 1,
                            FundedMaxDrawdown = 3000m,
                            IsActive = true,
                            MaxDrawdown = 3000m,
                            MinTradingDays = 5,
                            Name = "Tradeify Advanced 100K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 6000m,
                            PropFirmId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000018"),
                            AccountSize = 150000m,
                            ActivationCost = 0m,
                            DailyLossLimit = 3750m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 275m,
                            FundedDailyLossLimit = 3750m,
                            FundedDrawdownType = 1,
                            FundedMaxDrawdown = 5000m,
                            IsActive = true,
                            MaxDrawdown = 5000m,
                            MinTradingDays = 5,
                            Name = "Tradeify Growth 150K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 9000m,
                            PropFirmId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000019"),
                            AccountSize = 25000m,
                            ActivationCost = 0m,
                            DailyLossLimit = 625m,
                            DrawdownType = 2,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 95m,
                            FundedDailyLossLimit = 625m,
                            FundedDrawdownType = 2,
                            FundedMaxDrawdown = 1000m,
                            IsActive = true,
                            MaxDrawdown = 1000m,
                            Name = "Lucid 25K",
                            PayoutMaxProfitPct = 0.50m,
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 1000m,
                            PropFirmId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            AccountSize = 50000m,
                            ActivationCost = 0m,
                            DailyLossLimit = 1250m,
                            DrawdownType = 2,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 137m,
                            FundedDailyLossLimit = 1250m,
                            FundedDrawdownType = 2,
                            FundedMaxDrawdown = 2000m,
                            IsActive = true,
                            MaxDrawdown = 2000m,
                            Name = "Lucid 50K",
                            PayoutMaxProfitPct = 0.50m,
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 2000m,
                            PropFirmId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            AccountSize = 100000m,
                            ActivationCost = 0m,
                            DailyLossLimit = 2500m,
                            DrawdownType = 2,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 267m,
                            FundedDailyLossLimit = 2500m,
                            FundedDrawdownType = 2,
                            FundedMaxDrawdown = 3000m,
                            IsActive = true,
                            MaxDrawdown = 3000m,
                            Name = "Lucid 100K",
                            PayoutMaxProfitPct = 0.50m,
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 4000m,
                            PropFirmId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000020"),
                            AccountSize = 150000m,
                            ActivationCost = 0m,
                            DailyLossLimit = 3750m,
                            DrawdownType = 2,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 365m,
                            FundedDailyLossLimit = 3750m,
                            FundedDrawdownType = 2,
                            FundedMaxDrawdown = 4500m,
                            IsActive = true,
                            MaxDrawdown = 4500m,
                            Name = "Lucid 150K",
                            PayoutMaxProfitPct = 0.50m,
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 6000m,
                            PropFirmId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            AccountSize = 50000m,
                            ActivationCost = 149m,
                            DailyLossLimit = 1000m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 165m,
                            FundedDailyLossLimit = 1000m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 2000m,
                            IsActive = true,
                            MaxDrawdown = 2000m,
                            MinTradingDays = 5,
                            Name = "Topstep 50K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 3000m,
                            PropFirmId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            AccountSize = 100000m,
                            ActivationCost = 149m,
                            DailyLossLimit = 2000m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 245m,
                            FundedDailyLossLimit = 2000m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 3000m,
                            IsActive = true,
                            MaxDrawdown = 3000m,
                            MinTradingDays = 5,
                            Name = "Topstep 100K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 6000m,
                            PropFirmId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000021"),
                            AccountSize = 150000m,
                            ActivationCost = 149m,
                            DailyLossLimit = 3000m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 199m,
                            FundedDailyLossLimit = 3000m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 4500m,
                            IsActive = true,
                            MaxDrawdown = 4500m,
                            MinTradingDays = 5,
                            Name = "Topstep 150K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 9000m,
                            PropFirmId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000022"),
                            AccountSize = 25000m,
                            ActivationCost = 0m,
                            ConsistencyMaxDayFraction = 0.50m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 120m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 1000m,
                            IsActive = true,
                            MaxDrawdown = 1000m,
                            Name = "MFF Rapid 25K",
                            PayoutMinDaysBetween = 5,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 1500m,
                            PropFirmId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            AccountSize = 50000m,
                            ActivationCost = 0m,
                            ConsistencyMaxDayFraction = 0.50m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 165m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 2000m,
                            IsActive = true,
                            MaxDrawdown = 2000m,
                            Name = "MFF Rapid 50K",
                            PayoutMinDaysBetween = 5,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 3000m,
                            PropFirmId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            AccountSize = 100000m,
                            ActivationCost = 0m,
                            ConsistencyMaxDayFraction = 0.50m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 250m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 3000m,
                            IsActive = true,
                            MaxDrawdown = 3000m,
                            Name = "MFF Rapid 100K",
                            PayoutMinDaysBetween = 5,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 6000m,
                            PropFirmId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000023"),
                            AccountSize = 150000m,
                            ActivationCost = 0m,
                            ConsistencyMaxDayFraction = 0.50m,
                            DrawdownType = 0,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 320m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 4500m,
                            IsActive = true,
                            MaxDrawdown = 4500m,
                            Name = "MFF Rapid 150K",
                            PayoutMinDaysBetween = 5,
                            PayoutSplitTraderPct = 0.90m,
                            ProfitTarget = 9000m,
                            PropFirmId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000024"),
                            AccountSize = 25000m,
                            ActivationCost = 130m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 150m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 1500m,
                            IsActive = true,
                            MaxDrawdown = 1500m,
                            MinTradingDays = 5,
                            Name = "TPT 25K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 1500m,
                            PropFirmId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            AccountSize = 50000m,
                            ActivationCost = 130m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 150m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 2000m,
                            IsActive = true,
                            MaxDrawdown = 2000m,
                            MinTradingDays = 5,
                            Name = "TPT 50K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 3000m,
                            PropFirmId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000025"),
                            AccountSize = 75000m,
                            ActivationCost = 130m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 185m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 3000m,
                            IsActive = true,
                            MaxDrawdown = 3000m,
                            MinTradingDays = 5,
                            Name = "TPT 75K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 4500m,
                            PropFirmId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            AccountSize = 100000m,
                            ActivationCost = 130m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 220m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 3000m,
                            IsActive = true,
                            MaxDrawdown = 3000m,
                            MinTradingDays = 5,
                            Name = "TPT 100K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 6000m,
                            PropFirmId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000026"),
                            AccountSize = 150000m,
                            ActivationCost = 130m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 300m,
                            FundedDrawdownType = 0,
                            FundedMaxDrawdown = 4500m,
                            IsActive = true,
                            MaxDrawdown = 4500m,
                            MinTradingDays = 5,
                            Name = "TPT 150K",
                            PayoutMinDaysBetween = 14,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 9000m,
                            PropFirmId = new Guid("66666666-6666-6666-6666-666666666666")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000014"),
                            AccountSize = 50000m,
                            ActivationCost = 0m,
                            ConsistencyMaxDayFraction = 0.30m,
                            DailyLossLimit = 1100m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 245m,
                            FundedDrawdownType = 1,
                            FundedMaxDrawdown = 2000m,
                            IsActive = true,
                            MaxDrawdown = 2000m,
                            MinTradingDays = 10,
                            Name = "E2T Gauntlet Mini 50K",
                            PayoutMinDaysBetween = 30,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 3000m,
                            PropFirmId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000013"),
                            AccountSize = 100000m,
                            ActivationCost = 0m,
                            ConsistencyMaxDayFraction = 0.30m,
                            DailyLossLimit = 2200m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 430m,
                            FundedDrawdownType = 1,
                            FundedMaxDrawdown = 4000m,
                            IsActive = true,
                            MaxDrawdown = 4000m,
                            MinTradingDays = 10,
                            Name = "E2T Gauntlet Mini 100K",
                            PayoutMinDaysBetween = 30,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 6000m,
                            PropFirmId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000027"),
                            AccountSize = 150000m,
                            ActivationCost = 0m,
                            ConsistencyMaxDayFraction = 0.30m,
                            DailyLossLimit = 3300m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 600m,
                            FundedDrawdownType = 1,
                            FundedMaxDrawdown = 6000m,
                            IsActive = true,
                            MaxDrawdown = 6000m,
                            MinTradingDays = 10,
                            Name = "E2T Gauntlet Mini 150K",
                            PayoutMinDaysBetween = 30,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 9000m,
                            PropFirmId = new Guid("77777777-7777-7777-7777-777777777777")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000028"),
                            AccountSize = 200000m,
                            ActivationCost = 0m,
                            ConsistencyMaxDayFraction = 0.30m,
                            DailyLossLimit = 4400m,
                            DrawdownType = 1,
                            EffectiveFrom = new DateOnly(2026, 1, 1),
                            EvaluationCost = 750m,
                            FundedDrawdownType = 1,
                            FundedMaxDrawdown = 8000m,
                            IsActive = true,
                            MaxDrawdown = 8000m,
                            MinTradingDays = 10,
                            Name = "E2T Gauntlet Mini 200K",
                            PayoutMinDaysBetween = 30,
                            PayoutSplitTraderPct = 0.80m,
                            ProfitTarget = 12000m,
                            PropFirmId = new Guid("77777777-7777-7777-7777-777777777777")
                        });
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Commission")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Side")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.HasIndex("AccountId", "ExecutedAt");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("Executions", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Root")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("TickValue")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Root")
                        .IsUnique();

                    b.ToTable("Instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000001"),
                            Name = "E-mini S&P 500",
                            Root = "ES",
                            TickSize = 0.25m,
                            TickValue = 12.50m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000002"),
                            Name = "Micro E-mini S&P 500",
                            Root = "MES",
                            TickSize = 0.25m,
                            TickValue = 1.25m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000003"),
                            Name = "E-mini Nasdaq-100",
                            Root = "NQ",
                            TickSize = 0.25m,
                            TickValue = 5.00m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000004"),
                            Name = "Micro E-mini Nasdaq-100",
                            Root = "MNQ",
                            TickSize = 0.25m,
                            TickValue = 0.50m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000005"),
                            Name = "Gold Futures",
                            Root = "GC",
                            TickSize = 0.10m,
                            TickValue = 10.00m
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-0000-0000-0000-000000000006"),
                            Name = "Crude Oil Futures",
                            Root = "CL",
                            TickSize = 0.01m,
                            TickValue = 10.00m
                        });
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.IntegrationSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProtectedValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Key");

                    b.ToTable("IntegrationSettings", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountRequested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly?>("PaidOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("RequestedOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RequestedOn");

                    b.ToTable("Payouts", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.ProcessedWebhookEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProcessedWebhookEvents", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.PropFirm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("MinDaysBetweenPayouts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PropFirms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Lucid Trading",
                            Website = "https://lucidtrading.com"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Tradeify",
                            Website = "https://tradeify.co"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Apex Trader Funding",
                            Website = "https://apextraderfunding.com"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Topstep",
                            Website = "https://topstep.com"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "MyFundedFutures",
                            Website = "https://myfundedfutures.com"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Take Profit Trader",
                            Website = "https://takeprofittrader.com"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Earn2Trade",
                            Website = "https://earn2trade.com"
                        });
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.PublicProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShareEmotions")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShareOperativa")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("PublicProfiles", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvgEntryPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("AvgExitPrice")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Commissions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<decimal>("GrossPnL")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxAdverseExcursion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxFavorableExcursion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RiskedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tags")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("AccountId", "ClosedAt");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.TradeEmotionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Adherence")
                        .HasColumnType("integer");

                    b.Property<int>("Emotion")
                        .HasColumnType("integer");

                    b.Property<int>("Intensity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Moment")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasImpulsive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeEmotionLogs", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.TradeSetup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("TradeSetups", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.TradingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AccountSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DrawdownType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("EvaluationProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Feed")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FundedOn")
                        .HasColumnType("date");

                    b.Property<decimal>("MaxDrawdown")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("ProfitTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PropFirmId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PurchasedOn")
                        .HasColumnType("date");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationProgramId");

                    b.HasIndex("PropFirmId");

                    b.HasIndex("Stage");

                    b.HasIndex("UserId");

                    b.ToTable("TradingAccounts", (string)null);
                });

            modelBuilder.Entity("TrackRecord.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("PlanTier")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TrackRecord.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TrackRecord.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackRecord.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TrackRecord.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.AccountCost", b =>
                {
                    b.HasOne("TrackRecord.Domain.Entities.TradingAccount", "Account")
                        .WithMany("Costs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.AccountEvent", b =>
                {
                    b.HasOne("TrackRecord.Domain.Entities.TradingAccount", "Account")
                        .WithMany("Events")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.EvaluationProgram", b =>
                {
                    b.HasOne("TrackRecord.Domain.Entities.PropFirm", "PropFirm")
                        .WithMany()
                        .HasForeignKey("PropFirmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackRecord.Domain.Entities.PropFirm", null)
                        .WithMany("Programs")
                        .HasForeignKey("PropFirmId1");

                    b.Navigation("PropFirm");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.Execution", b =>
                {
                    b.HasOne("TrackRecord.Domain.Entities.TradingAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackRecord.Domain.Entities.Trade", "Trade")
                        .WithMany("Executions")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.Payout", b =>
                {
                    b.HasOne("TrackRecord.Domain.Entities.TradingAccount", "Account")
                        .WithMany("Payouts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.Trade", b =>
                {
                    b.HasOne("TrackRecord.Domain.Entities.TradingAccount", "Account")
                        .WithMany("Trades")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TrackRecord.Domain.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.TradeEmotionLog", b =>
                {
                    b.HasOne("TrackRecord.Domain.Entities.Trade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.TradingAccount", b =>
                {
                    b.HasOne("TrackRecord.Domain.Entities.EvaluationProgram", "EvaluationProgram")
                        .WithMany()
                        .HasForeignKey("EvaluationProgramId");

                    b.HasOne("TrackRecord.Domain.Entities.PropFirm", "PropFirm")
                        .WithMany("Accounts")
                        .HasForeignKey("PropFirmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EvaluationProgram");

                    b.Navigation("PropFirm");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.PropFirm", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Programs");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.Trade", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("TrackRecord.Domain.Entities.TradingAccount", b =>
                {
                    b.Navigation("Costs");

                    b.Navigation("Events");

                    b.Navigation("Payouts");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
